// Authentication
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";
export const USER_LOADED = "USER_LOADED";
export const USER_LOADING = "USER_LOADING";

// Errors
export const AUTH_ERROR = "AUTH_ERROR";


// Wizard
export const CLEAR_FIELDS = "CLEAR_FIELDS";
export const UPDATE_FIELD = "UPDATE_FIELD";
export const UPDATE_COACH_FIELDS = "UPDATE_COACH_FIELDS";
export const UPDATE_PLAYER_FIELDS = "UPDATE_PLAYER_FIELDS";
export const UPDATE_MEDIA_FIELDS = "UPDATE_MEDIA_FIELDS";
export const UPDATE_FAN_FIELDS = "UPDATE_FAN_FIELDS";
export const UPDATE_AGENT_FIELDS = "UPDATE_AGENT_FIELDS";

